name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up Node.js
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Install deps
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn lint
      - name: Run formatter check
        run: |
          yarn run --silent format-check || ( \
            echo "Run this command on your local device to fix the error:" && \
            echo "" && \
            echo "  yarn run format" && \
            echo "" && exit 1)